area_info:
  gdf_dir_path: asset/area_geojson
  area_info_sqlite_path: asset/area_code.sqlite

traffic_sign:
  color:
    red: '#B5273C'
    white: '#FFFFFF'
    yellow: '#FFCD00'
    black: '#000000'
    green: '#006E55'
  font_path:
    A: asset/font/SourceHanSansSC-Bold.otf
    B: asset/font/jtbz_B.ttf
    C: asset/font/jtbz_C.ttf
  way_num_pad:
    template: asset/template_path/way_num.svg
  expwy_code_sign:
    without_name:
      num_1:
        template: asset/template_path/expwy_1.svg
      num_2:
        template: asset/template_path/expwy_2.svg
      num_4:
        template: asset/template_path/expwy_4.svg
    with_name:
      num_1:
        template: asset/template_path/expwy_1_name.svg
      num_2:
        template: asset/template_path/expwy_2_name.svg
      num_4:
        template: asset/template_path/expwy_4_name.svg

video_info_layer:
  font_path:
    chinese: asset/font/SourceHanSans_static_super_otc.ttc
    chinese_index: 12
    english: asset/font/SourceSans3-Regular.otf
  img_path:
    compass: asset/compass.svg
    route_time_sep: asset/route_time_sep.svg\
  frame:
    width: 3840
    height: 2160
    dpi: 72
    min_space: 48
    area:
      chinese:
        x: 191.8085
        y: 1924
      english:
        x: 192
        y: 1997
    road:
      x: 1464
      middle_y: 1988
      sign:
        width: 126
        height: 128
        space: 24
        char_space: 48
      chinese_y: 1924
      english_y: 1997
    compass:
      x: 2432
      y: 1924
    route_time:
      used:
        route:
          right_x: 2978
          y: 1924
        time:
          right_x: 2978
          y: 1997
      sep:
        x: 3002
        y: 1924
      remain:
        route:
          x: 3117
          y: 1924
        time:
          x: 3117
          y: 1997
    altitude:
      num:
        right_x: 3483
        y: 1924
      unit:
        right_x: 3483
        y: 1997
    speed:
      num:
        right_x: 3649
        y: 1924
      unit:
        right_x: 3649
        y: 1997